#!/bin/sh
set -e

. "$(dirname "$0")/_/husky.sh"

BRANCH=$(git rev-parse --abbrev-ref HEAD)
DIFF=$(git diff origin/$BRANCH..HEAD)

if [ "$DIFF" != "" ] 
then
  echo "There are changes to be pushed"
  pnpm build && pnpm test
else
  echo "No changes to be pushed, skipping build & test"
fi

